# Configuration simplifiée pour GitHub Labeler
# Format: 'label': ['pattern1', 'pattern2', ...]

# Backend changes
'backend':
  - 'backend/**'
  - '**/*.py'
  - '!frontend/**'
  - '!docs/**'

# Frontend changes
'frontend':
  - 'frontend/**'
  - '**/*.ts'
  - '**/*.tsx'
  - '**/*.js'
  - '**/*.jsx'
  - '**/*.css'
  - '**/*.scss'
  - '!backend/**'
  - '!docs/**'

# CI/CD changes
'ci':
  - '.github/workflows/**'
  - '.github/actions/**'
  - '**/*.yml'
  - '**/*.yaml'
  - '!**/node_modules/**'
  - '!**/dist/**'
  - '!**/build/**'

# Documentation changes
'docs':
  - 'docs/**'
  - 'mkdocs.yml'
  - '**/*.md'
  - '!**/node_modules/**'
  - '!**/dist/**'
  - '!**/build/**'

# End-to-end tests
'e2e':
  - 'frontend/tests/e2e/**'

# Security-related changes
'security':
  - 'backend/requirements*.txt'
  - 'frontend/package*.json'
