# Label pour les modifications dans le backend
'backend':
  - 'backend/**'
  - '**/*.py'
  - '!frontend/**'
  - '!docs/**'

# Label pour les modifications dans le frontend
'frontend':
  - 'frontend/**'
  - '**/*.ts'
  - '**/*.tsx'
  - '**/*.js'
  - '**/*.jsx'
  - '**/*.css'
  - '**/*.scss'
  - '!backend/**'
  - '!docs/**'

# Label pour les modifications dans la CI/CD
'ci':
  - '.github/workflows/**'
  - '.github/actions/**'
  - '**/*.yml'
  - '**/*.yaml'
  - '!**/node_modules/**'
  - '!**/dist/**'
  - '!**/build/**'

# Label pour les modifications dans la documentation
'docs':
  - 'docs/**'
  - 'mkdocs.yml'
  - '**/*.md'
  - '!**/node_modules/**'
  - '!**/dist/**'
  - '!**/build/**'

# Label pour les tests end-to-end
'e2e':
  - 'frontend/tests/e2e/**'

# Label pour les modifications liées à la sécurité
'security':
  - 'backend/requirements*.txt'
  - 'frontend/package*.json'
