# Minimal configuration for GitHub Labeler
# Format: 'label': 'pattern'

'backend': '**/*.py'
'frontend': '**/*.{ts,tsx,js,jsx,css,scss}'
'ci': '.github/**/*.{yml,yaml}'
'docs': '**/*.md'
'e2e': 'frontend/tests/e2e/**'
'security': '**/package*.json'
