# Configuration for GitHub Labeler v5
# Format: 
# label-name:
#   - pattern1
#   - pattern2

backend:
  - '**/*.py'

frontend:
  - '**/*.ts'
  - '**/*.tsx'
  - '**/*.js'
  - '**/*.jsx'
  - '**/*.css'
  - '**/*.scss'

ci:
  - '.github/workflows/*.yml'
  - '.github/workflows/*.yaml'
  - '.github/actions/**/*.yml'
  - '.github/actions/**/*.yaml'

docs:
  - '**/*.md'
  - '**/*.mdx'

e2e:
  - 'frontend/tests/e2e/**'

security:
  - '**/package*.json'
  - '**/*.lock'
