# Minimal configuration for GitHub Labeler
# Format for actions/labeler@v3

# Backend files
'backend':
  - '**/*.py'

# Frontend files
'frontend':
  - '**/*.ts'
  - '**/*.tsx'
  - '**/*.js'
  - '**/*.jsx'
  - '**/*.css'
  - '**/*.scss'

# CI/CD files
'ci':
  - '.github/workflows/*'
  - '.github/actions/*'
  - '**/*.yml'
  - '**/*.yaml'

# Documentation
'docs':
  - '**/*.md'

# End-to-end tests
'e2e':
  - 'frontend/tests/e2e/**'

# Security related files
'security':
  - '**/package*.json'
