# Label pour les modifications dans le backend
'backend':
  - changed-files:
    - any:
      - 'backend/**'
      - '**/*.py'
    exclude:
      - 'frontend/**'
      - 'docs/**'

# Label pour les modifications dans le frontend
'frontend':
  - changed-files:
    - any:
      - 'frontend/**'
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.js'
      - '**/*.jsx'
      - '**/*.css'
      - '**/*.scss'
    exclude:
      - 'backend/**'
      - 'docs/**'

# Label pour les modifications dans la CI/CD
'ci':
  - changed-files:
    - any:
      - '.github/workflows/**'
      - '.github/actions/**'
      - '**/*.yml'
      - '**/*.yaml'
    exclude:
      - '**/node_modules/**'
      - '**/dist/**'
      - '**/build/**'

# Label pour les modifications dans la documentation
'docs':
  - changed-files:
    - any:
      - 'docs/**'
      - 'mkdocs.yml'
      - '**/*.md'
    exclude:
      - '**/node_modules/**'
      - '**/dist/**'
      - '**/build/**'

# Label pour les tests end-to-end
'e2e':
  - changed-files:
    - any:
      - 'frontend/tests/e2e/**'

# Label pour les modifications liées à la sécurité
'security':
  - changed-files:
    - any:
      - 'backend/requirements*.txt'
      - 'frontend/package*.json'
