"""Build suggestion persistence model."""

import uuid

from sqlalchemy import Column, DateTime, ForeignKey, Index, JSON, Text
from sqlalchemy.sql import func

from app.db.base_class import Base
from app.db.types import GUID


class BuildSuggestionDB(Base):
    """SQLAlchemy model storing build suggestions generated by the AI."""

    __tablename__ = "build_suggestions"

    id = Column(GUID(), primary_key=True, default=uuid.uuid4)
    user_id = Column(GUID(), ForeignKey("users.id", ondelete="SET NULL"), nullable=True, index=True)
    build = Column(JSON, nullable=False)
    explanation = Column(Text, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False, index=True)

    __table_args__ = (Index("ix_build_suggestions_user_created_at", "user_id", "created_at"),)
