"""Add builds and teams tables with relationships

Revision ID: 232b6ca2fb3c
Revises: 3940a8aceff4
Create Date: 2025-10-20 10:15:24.767497

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "232b6ca2fb3c"
down_revision: Union[str, None] = "3940a8aceff4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "builds",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("profession", sa.String(length=50), nullable=False),
        sa.Column("specialization", sa.String(length=100), nullable=True),
        sa.Column("game_mode", sa.String(length=50), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("trait_lines", sa.JSON(), nullable=False),
        sa.Column("skills", sa.JSON(), nullable=False),
        sa.Column("equipment", sa.JSON(), nullable=False),
        sa.Column("synergies", sa.JSON(), nullable=False),
        sa.Column("counters", sa.JSON(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("playstyle", sa.Text(), nullable=True),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column("source_type", sa.String(length=50), nullable=True),
        sa.Column("effectiveness", sa.Float(), nullable=True),
        sa.Column("difficulty", sa.Integer(), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_builds_game_mode"), "builds", ["game_mode"], unique=False)
    op.create_index(op.f("ix_builds_id"), "builds", ["id"], unique=False)
    op.create_index(op.f("ix_builds_is_public"), "builds", ["is_public"], unique=False)
    op.create_index(op.f("ix_builds_name"), "builds", ["name"], unique=False)
    op.create_index(op.f("ix_builds_profession"), "builds", ["profession"], unique=False)
    op.create_index(op.f("ix_builds_role"), "builds", ["role"], unique=False)
    op.create_index(op.f("ix_builds_user_id"), "builds", ["user_id"], unique=False)
    op.create_table(
        "team_compositions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("game_mode", sa.String(length=50), nullable=False),
        sa.Column("team_size", sa.Integer(), nullable=False),
        sa.Column("synergies", sa.JSON(), nullable=False),
        sa.Column("weaknesses", sa.JSON(), nullable=False),
        sa.Column("strengths", sa.JSON(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("overall_rating", sa.Float(), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_team_compositions_game_mode"), "team_compositions", ["game_mode"], unique=False)
    op.create_index(op.f("ix_team_compositions_id"), "team_compositions", ["id"], unique=False)
    op.create_index(op.f("ix_team_compositions_is_public"), "team_compositions", ["is_public"], unique=False)
    op.create_index(op.f("ix_team_compositions_name"), "team_compositions", ["name"], unique=False)
    op.create_index(op.f("ix_team_compositions_user_id"), "team_compositions", ["user_id"], unique=False)
    op.create_table(
        "team_builds",
        sa.Column("team_composition_id", sa.String(), nullable=False),
        sa.Column("build_id", sa.String(), nullable=False),
        sa.Column("slot_number", sa.Integer(), nullable=False),
        sa.Column("player_name", sa.String(length=100), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["build_id"], ["builds.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["team_composition_id"], ["team_compositions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("team_composition_id", "build_id"),
    )
    op.create_table(
        "team_slots",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("team_composition_id", sa.String(), nullable=False),
        sa.Column("build_id", sa.String(), nullable=False),
        sa.Column("slot_number", sa.Integer(), nullable=False),
        sa.Column("player_name", sa.String(length=100), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["build_id"], ["builds.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["team_composition_id"], ["team_compositions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_team_slots_build_id"), "team_slots", ["build_id"], unique=False)
    op.create_index(op.f("ix_team_slots_id"), "team_slots", ["id"], unique=False)
    op.create_index(op.f("ix_team_slots_team_composition_id"), "team_slots", ["team_composition_id"], unique=False)
    op.alter_column("users", "is_active", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("users", "is_superuser", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("users", "created_at", existing_type=sa.DATETIME(), nullable=False)
    op.alter_column("users", "updated_at", existing_type=sa.DATETIME(), nullable=False)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.alter_column("users", "updated_at", existing_type=sa.DATETIME(), nullable=True)
    op.alter_column("users", "created_at", existing_type=sa.DATETIME(), nullable=True)
    op.alter_column("users", "is_superuser", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("users", "is_active", existing_type=sa.BOOLEAN(), nullable=True)
    op.drop_index(op.f("ix_team_slots_team_composition_id"), table_name="team_slots")
    op.drop_index(op.f("ix_team_slots_id"), table_name="team_slots")
    op.drop_index(op.f("ix_team_slots_build_id"), table_name="team_slots")
    op.drop_table("team_slots")
    op.drop_table("team_builds")
    op.drop_index(op.f("ix_team_compositions_user_id"), table_name="team_compositions")
    op.drop_index(op.f("ix_team_compositions_name"), table_name="team_compositions")
    op.drop_index(op.f("ix_team_compositions_is_public"), table_name="team_compositions")
    op.drop_index(op.f("ix_team_compositions_id"), table_name="team_compositions")
    op.drop_index(op.f("ix_team_compositions_game_mode"), table_name="team_compositions")
    op.drop_table("team_compositions")
    op.drop_index(op.f("ix_builds_user_id"), table_name="builds")
    op.drop_index(op.f("ix_builds_role"), table_name="builds")
    op.drop_index(op.f("ix_builds_profession"), table_name="builds")
    op.drop_index(op.f("ix_builds_name"), table_name="builds")
    op.drop_index(op.f("ix_builds_is_public"), table_name="builds")
    op.drop_index(op.f("ix_builds_id"), table_name="builds")
    op.drop_index(op.f("ix_builds_game_mode"), table_name="builds")
    op.drop_table("builds")
    # ### end Alembic commands ###
