"""Initial database schema with GW2 entities

Revision ID: 56421d6d32db
Revises: 
Create Date: 2025-10-28 00:58:02.992607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56421d6d32db'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gw2_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=512), nullable=True),
    sa.Column('type', sa.Enum('ARMOR', 'TRINKET', 'WEAPON', 'CONSUMABLE', name='item_type'), nullable=False),
    sa.Column('rarity', sa.String(length=50), nullable=True),
    sa.Column('stats_json', sa.JSON(), nullable=False),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('etag', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gw2_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gw2_items_etag'), ['etag'], unique=False)
        batch_op.create_index(batch_op.f('ix_gw2_items_name'), ['name'], unique=False)

    op.create_table('gw2_professions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=512), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('primary_attributes', sa.JSON(), nullable=False),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('etag', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gw2_professions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gw2_professions_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_gw2_professions_etag'), ['etag'], unique=False)
        batch_op.create_index(batch_op.f('ix_gw2_professions_name'), ['name'], unique=True)

    op.create_table('gw2_weapons',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=512), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('two_handed', sa.Boolean(), nullable=False),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('etag', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gw2_weapons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gw2_weapons_etag'), ['etag'], unique=False)
        batch_op.create_index(batch_op.f('ix_gw2_weapons_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_gw2_weapons_type'), ['type'], unique=False)

    op.create_table('gw2_builds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.Column('profession_id', sa.Integer(), nullable=False),
    sa.Column('specialization_order', sa.JSON(), nullable=False),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('etag', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profession_id'], ['gw2_professions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'profession_id', name='uq_build_name_profession')
    )
    with op.batch_alter_table('gw2_builds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gw2_builds_etag'), ['etag'], unique=False)
        batch_op.create_index(batch_op.f('ix_gw2_builds_name'), ['name'], unique=False)

    op.create_table('gw2_profession_weapons',
    sa.Column('profession_id', sa.Integer(), nullable=False),
    sa.Column('weapon_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['profession_id'], ['gw2_professions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['weapon_id'], ['gw2_weapons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profession_id', 'weapon_id')
    )
    op.create_table('gw2_specializations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=512), nullable=True),
    sa.Column('elite', sa.Boolean(), nullable=False),
    sa.Column('minor_traits', sa.JSON(), nullable=False),
    sa.Column('major_traits', sa.JSON(), nullable=False),
    sa.Column('profession_id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('etag', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profession_id'], ['gw2_professions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gw2_specializations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gw2_specializations_etag'), ['etag'], unique=False)
        batch_op.create_index(batch_op.f('ix_gw2_specializations_name'), ['name'], unique=True)

    op.create_table('gw2_build_items',
    sa.Column('build_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['gw2_builds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['gw2_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('build_id', 'item_id')
    )
    op.create_table('gw2_build_specializations',
    sa.Column('build_id', sa.Integer(), nullable=False),
    sa.Column('specialization_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['gw2_builds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['specialization_id'], ['gw2_specializations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('build_id', 'specialization_id')
    )
    op.create_table('gw2_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=512), nullable=True),
    sa.Column('type', sa.Enum('WEAPON', 'UTILITY', 'HEAL', 'ELITE', name='skill_type'), nullable=False),
    sa.Column('weapon_type', sa.String(length=50), nullable=True),
    sa.Column('profession_id', sa.Integer(), nullable=True),
    sa.Column('specialization_id', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('etag', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profession_id'], ['gw2_professions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['specialization_id'], ['gw2_specializations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gw2_skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gw2_skills_etag'), ['etag'], unique=False)
        batch_op.create_index(batch_op.f('ix_gw2_skills_name'), ['name'], unique=False)

    op.create_table('gw2_traits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=512), nullable=True),
    sa.Column('slot', sa.Enum('ADEPT', 'MASTER', 'GRANDMASTER', name='trait_slot'), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=False),
    sa.Column('specialization_id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('etag', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['specialization_id'], ['gw2_specializations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gw2_traits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gw2_traits_etag'), ['etag'], unique=False)
        batch_op.create_index(batch_op.f('ix_gw2_traits_name'), ['name'], unique=False)

    op.create_table('gw2_build_skills',
    sa.Column('build_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['gw2_builds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['gw2_skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('build_id', 'skill_id')
    )
    op.create_table('gw2_build_traits',
    sa.Column('build_id', sa.Integer(), nullable=False),
    sa.Column('trait_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['gw2_builds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trait_id'], ['gw2_traits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('build_id', 'trait_id')
    )
    op.create_table('gw2_skill_traits',
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('trait_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['gw2_skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trait_id'], ['gw2_traits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('skill_id', 'trait_id')
    )
    op.create_table('gw2_weapon_skills',
    sa.Column('weapon_id', sa.String(length=50), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['gw2_skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['weapon_id'], ['gw2_weapons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('weapon_id', 'skill_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gw2_weapon_skills')
    op.drop_table('gw2_skill_traits')
    op.drop_table('gw2_build_traits')
    op.drop_table('gw2_build_skills')
    with op.batch_alter_table('gw2_traits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gw2_traits_name'))
        batch_op.drop_index(batch_op.f('ix_gw2_traits_etag'))

    op.drop_table('gw2_traits')
    with op.batch_alter_table('gw2_skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gw2_skills_name'))
        batch_op.drop_index(batch_op.f('ix_gw2_skills_etag'))

    op.drop_table('gw2_skills')
    op.drop_table('gw2_build_specializations')
    op.drop_table('gw2_build_items')
    with op.batch_alter_table('gw2_specializations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gw2_specializations_name'))
        batch_op.drop_index(batch_op.f('ix_gw2_specializations_etag'))

    op.drop_table('gw2_specializations')
    op.drop_table('gw2_profession_weapons')
    with op.batch_alter_table('gw2_builds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gw2_builds_name'))
        batch_op.drop_index(batch_op.f('ix_gw2_builds_etag'))

    op.drop_table('gw2_builds')
    with op.batch_alter_table('gw2_weapons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gw2_weapons_type'))
        batch_op.drop_index(batch_op.f('ix_gw2_weapons_name'))
        batch_op.drop_index(batch_op.f('ix_gw2_weapons_etag'))

    op.drop_table('gw2_weapons')
    with op.batch_alter_table('gw2_professions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gw2_professions_name'))
        batch_op.drop_index(batch_op.f('ix_gw2_professions_etag'))
        batch_op.drop_index(batch_op.f('ix_gw2_professions_code'))

    op.drop_table('gw2_professions')
    with op.batch_alter_table('gw2_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gw2_items_name'))
        batch_op.drop_index(batch_op.f('ix_gw2_items_etag'))

    op.drop_table('gw2_items')
    # ### end Alembic commands ###
