from typing import Dict


StatDict = Dict[str, int]


PREFIX_REGISTRY: Dict[str, StatDict] = {
    "Berserker": {
        "power": 2800,
        "precision": 2200,
        "ferocity": 1200,
        "toughness": 1000,
        "vitality": 1000,
        "condition_damage": 0,
        "expertise": 0,
        "concentration": 0,
        "healing_power": 0,
    },
    "Marauder": {
        "power": 2600,
        "precision": 2300,
        "ferocity": 900,
        "toughness": 1000,
        "vitality": 1400,
        "condition_damage": 0,
        "expertise": 0,
        "concentration": 0,
        "healing_power": 0,
    },
    "Dragon": {
        "power": 2700,
        "precision": 2100,
        "ferocity": 900,
        "toughness": 1100,
        "vitality": 1300,
        "condition_damage": 0,
        "expertise": 0,
        "concentration": 0,
        "healing_power": 0,
    },
    "Valkyrie": {
        "power": 2600,
        "precision": 1200,
        "ferocity": 1200,
        "toughness": 1000,
        "vitality": 1500,
        "condition_damage": 0,
        "expertise": 0,
        "concentration": 0,
        "healing_power": 0,
    },
    "Minstrel": {
        "power": 1300,
        "precision": 1000,
        "ferocity": 0,
        "toughness": 1700,
        "vitality": 1700,
        "condition_damage": 0,
        "expertise": 0,
        "concentration": 1400,
        "healing_power": 1200,
    },
    "Harrier": {
        "power": 1600,
        "precision": 1200,
        "ferocity": 0,
        "toughness": 1300,
        "vitality": 1300,
        "condition_damage": 0,
        "expertise": 0,
        "concentration": 1500,
        "healing_power": 1700,
    },
    "Cleric": {
        "power": 1500,
        "precision": 900,
        "ferocity": 0,
        "toughness": 1400,
        "vitality": 1500,
        "condition_damage": 0,
        "expertise": 0,
        "concentration": 800,
        "healing_power": 2000,
    },
    "Magi": {
        "power": 900,
        "precision": 1200,
        "ferocity": 0,
        "toughness": 1100,
        "vitality": 1700,
        "condition_damage": 0,
        "expertise": 0,
        "concentration": 800,
        "healing_power": 1900,
    },
    "Diviner": {
        "power": 1900,
        "precision": 1500,
        "ferocity": 700,
        "toughness": 1200,
        "vitality": 1200,
        "condition_damage": 0,
        "expertise": 0,
        "concentration": 1700,
        "healing_power": 500,
    },
    "Soldier": {
        "power": 1900,
        "precision": 1200,
        "ferocity": 400,
        "toughness": 1900,
        "vitality": 1900,
        "condition_damage": 0,
        "expertise": 0,
        "concentration": 800,
        "healing_power": 400,
    },
    "Trailblazer": {
        "power": 900,
        "precision": 900,
        "ferocity": 0,
        "toughness": 1800,
        "vitality": 1800,
        "condition_damage": 1600,
        "expertise": 1300,
        "concentration": 0,
        "healing_power": 0,
    },
    "Dire": {
        "power": 800,
        "precision": 800,
        "ferocity": 0,
        "toughness": 1700,
        "vitality": 1700,
        "condition_damage": 1600,
        "expertise": 1100,
        "concentration": 0,
        "healing_power": 0,
    },
}


def get_prefix_stats(name: str) -> StatDict:
    stats = PREFIX_REGISTRY.get(name)
    if stats is None:
        raise KeyError(f"Unknown gear prefix: {name!r}")
    return dict(stats)
